project:
  type: website
  output-dir: docs

website:
  title: "Teaching DEIJ-infused Biostatistics"
  site-url: https://nwakim.github.io/DEIJ-biostats
  description: ""
  navbar:
    title: false
    left: 
      - icon: house-fill
        file: index.qmd
    background: primary
    search: true
    right:
      - href: datasets.qmd
        text: Datasets
      - href: resources.qmd
        text: Resources

format:
  html:
    theme:
      - sandstone_NW.scss
    toc: true
    

editor: visual

