---
title: "Teaching Dataset Repository"
page-layout: full
margin-header: signup.html
format: 
  html: 
    listing: 
      - id: datasets
        contents: datasets
        type: grid
        fields: [date, title, categories, description, reading-time]
        table-hover: true
        filter-ui: true
        categories: true
        feed: true
    toc: false
---

::: callout-caution
## Using these datasets in your classroom

If you are speaking about social issues and you have not experienced the consequences/oppression/bias associated with the issue, please take time to educate yourself on the experiences of folks who have. Within each dataset page, I have included some references to get you started on this.
:::

This repository is not meant to be the only resource or attempt to do the work of other, existing resources. There are many wonderful, socially inclined resources (like [ICSPR](https://www.icpsr.umich.edu/web/pages/index.html)) and statistically inclined resources, and teaching inclined resources. I hope to connect these three areas to make a repository that helps connect professors teaching statistics with statistical lessons and activities using socially motivated datasets that are publicly available.

**Please note that I am NOT formally trained in the social sciences.** For many of these datasets, I have asked colleagues who are experts in the respective fields to collaborate and critique my work.

**Finally, I am only ONE person. I am most certainly bringing bias into this work.** I have tried to counter my bias by collaborating with others, incorporating others' experiences, and researching various opinions. I encourage you to question my statements and perform your own research on each dataset.

## Dataset Pages

::: {#datasets}
:::

------------------------------------------------------------------------

------------------------------------------------------------------------

 

 

 

### My Notes for moving forward (not to be published) {.hidden}

-   Would like to publish this in: Journal of Statistics and Data Science Education or Statistics Education Rresearch Journal
-   Need to publish the site before making a subscribe button!!
-   Figure out how to sort datasets by lesson and/or social topic

#### Potentially good datasets from ICPSR: {.hidden}

-   [Behavioral Interventions to Advance Self-Sufficiency (BIAS) project](https://www.icpsr.umich.edu/web/ICPSR/studies/38319)

-   [**National Survey of Health Attitudes, \[United States\], 2018 (ICPSR 37633)**](https://www.icpsr.umich.edu/web/ICPSR/studies/37633)

    -   [With paper](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-021-10179-z)
    -   Paper uses logistic regression - collapses ordered Likert-type scale into two categories
        -   Compare the two options? logistic regression and ordinal logistic regresson
            -   Would we get different results? Which is more interpretable? When is a convenient choice worth making and how do we justify our choice?

-   [Social Adversity, Sleep Characteristics, and Elevated Blood Pressure Among Young Adult Black Females](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7585615/)

    -   <https://www.icpsr.umich.edu/web/ICPSR/studies/21600>

-   [**National Longitudinal Survey of Public Health Systems (NALSYS), \[United States\], 1998-2018 (ICPSR 23420)**](https://www.icpsr.umich.edu/web/ICPSR/studies/23420/publications)

    -   [With paper on longitudinal data](https://onlinelibrary.wiley.com/doi/10.1111/1468-0009.12553)

    -   [Logistic regression?](https://academyhealth.confex.com/academyhealth/2021arm/meetingapp.cgi/Paper/47105)

-   [A quantitative exploration of Queer-spectrum students’ experiences in introductory undergraduate mathematics courses](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0275325)

-   [Walking and Social Reminiscence in Gentrifying Neighborhoods: Feasibility and Impact on Cognitive, Physical, and Mental Health Among Older Black Adults in the SHARP Study](https://doi.org/10.1093/geront/gnae019)

#### Potential social topics for datasets: {.hidden}

-   Anti-fat bias (Debbie?)
-   Prison abolition? (Yves?)
-   Health equity focused on race
-   Precarious work, health, income
-   Substance use disorders? (Robin Baker?)
-   Neurodiversity
-   Health equity and agency over one's health in Native American communities?
    -   Perhaps something with taking care back to the community?

    -   *Important to be sensitive around issues/history around publicly available data*

    -   Jodi gave you data for BSTA 511 analysis!!!
-   Some work on women's health and improving research for female bodied people??
